// OG image is auto-generated by opengraph-image.tsx in this directory.
// Place a static og-image.png in apps/web/public/ for fallback.

import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar } from "../components/Navbar";
import { Footer } from "../components/Footer";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "StellarLearn — Learn Blockchain. Earn Crypto. Get Certified.",
  description:
    "Decentralized learn-to-earn platform for African blockchain developers. Complete courses, pass quizzes, and earn XLM/USDC rewards on Stellar.",
  openGraph: {
    title: "StellarLearn — Learn Blockchain. Earn Crypto. Get Certified.",
    description:
      "Decentralized learn-to-earn platform for African blockchain developers on Stellar.",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
